application: bl-ocks-org-hrd
version: 1
runtime: python27
threadsafe: no
api_version: 1

handlers:
- url: /
  static_files: static/about.html
  upload: static/about.html

- url: /style.css
  static_files: static/style.css
  upload: static/style.css

- url: /forkme.png
  static_files: static/forkme.png
  upload: static/forkme.png

- url: /highlight.min.js
  static_files: static/highlight.min.js
  upload: static/highlight.min.js

- url: .*
  script: main.py
